### ISSUE TITLE
visual studio 2013 projects appear to not be 2013 projects

### ISSUE THREAD

**Issue by blloyd75** [AprilAndFriends/theoraplayer#7]
When opening libtheoraplayer_vs2013.sln, the IDE prompts to upgrade to vs2013.
After the upgrade, it shows to still be using the vs2012 toolchain.
Reading the project files in a text editor shows the 2013 toolchain selected, as does the property pages.  However, the project tags as for 2012 - Windows XP and when a build is attempted it tries to use that toolchain.

It appears that all the projects in the solution are affected by this issue.

**Comment by blloyd75** [comment]
This is using Visual Studio Community 2013, Version 12.0.31101.00 Update 4

**Comment by blloyd75** [comment]
Commit 063ba24ba05df4d3f605c546b075caa31bf4983e is what broke the VS2013 build.  At that time it started using VS2012 as the build tools.  It also dropped DebugS and ReleaseS (static builds).

**Comment by borisblizzard** [comment]
Updated all VS projects (2012, 2013 and 2015). It should be fine now. Please close the issue after you check that everything works now.

**Comment by blloyd75** [comment]
Build tool selection appears correct, but there is now a problem with the build itself.

While the libraries show their dependencies, the samples do not.  Therefore, a rebuild on a multi-processor system will fail.  All libraries build properly, but the samples build faster than the libtheoraplayer they depend on, so they fail the link the step.
They just need the dependency on the libtheoraplayer to stop that issue from occurring.

I do not have Visual Studio 2012 available, nor 2015 installed.  So my testing is solely for VS2013.

Immediate workaround is to build again, since the libraries are already complete the samples then build.

**Comment by borisblizzard** [comment]
Fixed.

**Comment by blloyd75** [comment]
Looks good with latest commits for VS2003

**Comment by blloyd75** [comment]
Found that ReleaseS type projects attempt to build for vs14_xp, so toolset selection is still not always correct. demo_seek_set and demo_glut_player where affected.

**Comment by borisblizzard** [comment]
Not sure how I managed to mess that up.
It should all be fixed now. I checked all 4 configurations and all demos projects.
